export const USER_TEST_ACTION = 'USER_TEST_ACTION';
export const USER_INIT_PROFILE = 'USER_INIT_PROFILE';

export const WORDS_SET_WORDS = 'WORDS_SET_WORDS';
export const WORDS_FETCH_WORDS = 'WORDS_FETCH_WORDS';
export const WORDS_FETCH_WORDS_START = 'WORDS_FETCH_WORDS_START';
export const WORDS_FETCH_WORDS_SUCCESS = 'WORDS_FETCH_WORDS_SUCCESS';
export const WORDS_FETCH_WORDS_FAIL = 'WORDS_FETCH_WORDS_FAIL';
export const WORDS_SET_PRACTICE_RANGE = 'WORDS_SET_PRACTICE_RANGE';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const STAT_SET_USER_PROFILES = 'STAT_SET_USER_PROFILES';
export const STAT_FETCH_USER_PROFILES_START = 'STAT_FETCH_USER_PROFILES_START';
export const STAT_FETCH_USER_PROFILES_SUCCESS = 'STAT_FETCH_USER_PROFILES_SUCCESS';
export const STAT_FETCH_USER_PROFILES_FAIL = 'STAT_FETCH_USER_PROFILES_FAIL';
export const STAT_SET_WEEKLY_STAT = 'STAT_SET_WEEKLY_STAT';
export const STAT_FETCH_WEEKLY_STAT_START = 'STAT_FETCH_WEEKLY_STAT_START';
export const STAT_FETCH_WEEKLY_STAT_SUCCESS = 'STAT_FETCH_WEEKLY_STAT_SUCCESS';
export const STAT_FETCH_WEEKLY_STAT_FAIL = 'STAT_FETCH_WEEKLY_STAT_FAIL';
export const STAT_DISPLAY_WEEK_INCREMENT = 'STAT_DISPLAY_WEEK_INCREMENT';
export const STAT_DISPLAY_WEEK_DECREMENT = 'STAT_DISPLAY_WEEK_DECREMENT';
export const STAT_DISPLAY_WEEK_TO_CURRENT = 'STAT_DISPLAY_WEEK_TO_CURRENT';
export const STAT_DISPLAY_WEEK_SET = 'STAT_DISPLAY_WEEK_SET';

export const STAT_UPDATE_USER_PROFILE = 'STAT_UPDATE_USER_PROFILE';
export const STAT_UPDATE_USER_PROFILE_START = 'STAT_UPDATE_USER_PROFILE_START';
export const STAT_UPDATE_USER_PROFILE_SUCCESS = 'STAT_UPDATE_USER_PROFILE_SUCCESS';
export const STAT_UPDATE_USER_PROFILE_FAIL = 'STAT_UPDATE_USER_PROFILE_FAIL';
export const STAT_UPDATE_WEEKLY_STAT = 'USER_UPDATE_WEEKLY_STAT';
export const STAT_UPDATE_WEEKLY_STAT_START = 'USER_UPDATE_WEEKLY_STAT';
export const STAT_UPDATE_WEEKLY_STAT_SUCCESS = 'USER_UPDATE_WEEKLY_STAT';
export const STAT_UPDATE_WEEKLY_STAT_FAIL = 'USER_UPDATE_WEEKLY_STAT';